// @vitest-environment jsdom
import React from "react";
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import {
  TimelineCanvasViewport,
  type TimelineCanvasViewportProps,
} from "./TimelineCanvasViewport.js";
import type { Project } from "@stagesync/shared";

class MockResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
}
global.ResizeObserver = MockResizeObserver as unknown as typeof ResizeObserver;

describe("TimelineCanvasViewport", () => {
  const dummyProject: Project = {
    id: "p1",
    name: "Song",
    formatVersion: 6,
    updatedAt: new Date().toISOString(),
    ppq: 960,
    defaultBpm: 120,
    defaultMeter: { numerator: 4, denominator: 4 },
    forma: {
      clips: [
        {
          id: "f1",
          name: "Verse",
          kind: "section",
          startTicks: 0,
          lengthTicks: 3840,
        },
      ],
    },
    tempoMap: [{ id: "t1", bpm: 120, startTicks: 0 }],
    meterMap: [{ id: "m1", numerator: 4, denominator: 4, startTicks: 0 }],
    keyMap: [],
    akordy: { clips: [] },
    tekst: { clips: [] },
    melody: { clips: [] },
    cue: { clips: [] },
    scoreBarMap: { anchors: [] },
    audioTracks: [],
    audioClips: [],
    assets: [],
  };

  const baseProps = {
    inspectorOpen: false,
    uiScale: 1,
    effectiveZoomV: 1,
    timelineSurface: "timeline",
    draftProject: dummyProject,
    trackSelection: { kind: "none", ids: [], primaryId: null },
    soloAudioTrackIds: [],
    soloBusIds: [],
    selectedBusId: null,
    selectedHwOutputId: null,
    trackRename: null,
    busRename: null,
    buildChannelStripCallbacks: () => ({}),
    buildBusCallbacks: () => ({}),
    buildMasterStripCallbacks: {},
    onMetronomeToggle: vi.fn(),
    metronomeOn: false,
    playing: false,
    onAddAudioTrack: vi.fn(),
    onAddBus: vi.fn(),
    onAddHwOut: vi.fn(),
    onHwSelect: vi.fn(),
    onHwContextMenu: vi.fn(),
    onHwGainChange: vi.fn(),
    onHwMuteToggle: vi.fn(),
    onHwChannelModeChange: vi.fn(),
    canvasScrollRef: { current: null },
    canvasInnerWidth: "1200px",
    dockWidthBase: 120,
    markerOverlayRef: { current: null },
    showMidiPlayhead: true,
    playheadPx: 100,
    locatorPx: 150,
    viewSpan: { start: 0, end: 7680 },
    barTicks: 1920,
    effectiveLocatorTicks: 1920,
    locatorLabel: "2.1",
    onLocatorPointerDown: vi.fn(),
    onLocatorPointerMove: vi.fn(),
    onLocatorPointerUp: vi.fn(),
    eyeBtnRef: { current: null },
    eyeOpen: false,
    eyeMenuId: "eye-id",
    setEyeOpen: vi.fn(),
    touchTier: "desktop",
    beginDockWidthResize: vi.fn(),
    onDockWidthResizePointerMove: vi.fn(),
    endDockWidthResize: vi.fn(),
    effectiveZoomH: 1,
    loopRange: null,
    loopOn: false,
    barMarks: [],
    rulerBeatMarks: [],
    bindTrackRowsRef: vi.fn(),
    lanesCoordRef: { current: null },
    marqueeBox: null,
    trackVisibility: { forma: true },
    rowHeightStyle: () => ({ height: 40 }),
    laneHeights: {},
    zoomV: 1,
    tool: "pointer",
    onTool: vi.fn(),
    isMobilePreview: false,
    laneResizeTrackId: null,
    beginLaneResize: vi.fn(),
    onLaneResizePointerMove: vi.fn(),
    endLaneResize: vi.fn(),
    onLaneResizeDblClick: vi.fn(),
    onAudioTrackHeaderClick: vi.fn(),
    openAudioTrackContextMenu: vi.fn(),
    heldZoom: false,
    audioLaneDropId: null,
    setAudioLaneDropId: vi.fn(),
    onUploadAudioToTrack: vi.fn(),
    openEmptyLaneContextMenu: vi.fn(),
    beginMarquee: vi.fn(),
    beginTouchCanvasNav: vi.fn(),
    heldZoomRef: { current: false },
    onFormaLanePointerDown: vi.fn(),
    onMapLanePointerDown: vi.fn(),
    onFormaLanePointerMove: vi.fn(),
    onFormaLanePointerUp: vi.fn(),
    beginContentPencilDraw: vi.fn(),
    rawTicksAtClientX: () => 0,
    commitDraft: vi.fn(),
    clearMapSelection: vi.fn(),
    selectLaneClip: vi.fn(),
    laneImportTrackIdRef: { current: null },
    laneImportStartTicksRef: { current: null },
    laneAudioFileRef: { current: null },
    draftRef: { current: dummyProject },
    lanesRendererProps: null,
    clipSelection: { items: [], primaryId: null },
    failedAudioAssetIds: [],
    gestureSession: null,
    gesturePreview: null,
    primaryId: null,
    selectedAnchorId: null,
    mapDragPreview: null,
    tempoSegments: [],
    meterSegments: [],
    keySegments: [],
    tapActiveClipId: null,
    clearClipSelection: vi.fn(),
    setSelectedAnchorId: vi.fn(),
    setInspectorVisible: vi.fn(),
    setSongMetaOpen: vi.fn(),
    setMapSelection: vi.fn(),
    openMapEdit: vi.fn(),
    openClipContextMenu: vi.fn(),
    focusInspectorPanel: vi.fn(),
    onAudioClipPointerDown: vi.fn(),
    onFormaClipPointerDown: vi.fn(),
    onContentClipPointerDown: vi.fn(),
  } as unknown as TimelineCanvasViewportProps;

  it("renders timeline lanes view when surface is timeline", () => {
    render(<TimelineCanvasViewport {...baseProps} />);
    expect(
      screen.getByRole("slider", { name: "Locator wklejania" }),
    ).toBeTruthy();
  });
});
